name: Build and Run TGEP/Sandbox
on: [push]
    
jobs:
  build_and_test:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
      - name: Script
        run: cd build && ./build.ps1
        shell: pwsh
