name: Build and Run TGEP/Sandbox
on: [push]
    
jobs:
  build_and_test:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
      - name: CD
        shell: pwsh
        run: |
            .\build\build.ps1
